[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit BME280 Library@^2.1.2

; Build flags - feature toggles
build_flags =
  -D PIN_BME_SDA=1
  -D PIN_BME_SCL=2
  -D PIN_KY037_A=4
  -D PIN_PHOTO=6
  -D PIN_PMS_SET=7
  -D PIN_PMS_RX=17
  -D PIN_PMS_TX=18
  -D SAMPLE_INTERVAL_MS=10000
